In [73]:
from pymatgen.ext.matproj import MPRester
from pymatgen import Structure
from jupyter_jsmol.pymatgen import quick_view

from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

import numpy as np

In [74]:
with MPRester("qqtqIIM2PLMiknnf9nQO") as m: #Mettre ("USER_API_KEY")

    mp = "mp-15687"
    
    # Structure for material id
    structure = m.get_structure_by_material_id(mp)
    
    
#print (structure)

In [53]:
#Obtenir toutes les opérations de symétrie
sym = SpacegroupAnalyzer(structure).get_symmetry_operations(cartesian=False)
#print(sym)

In [75]:
#Symetrie 1 : (x,y,z) -> (x, y, -z)
print("Symetrie 1 : (x,y,z) -> (x,y,-z)")
print("Application d'un plan miroir -> Réflexion par rapport au plan(x,y)")# Miroir = Roto-Inversion d'ordre 2
print("Matrices de symétrie: \n",sym[3])

Symetrie 1 : (x,y,z) -> (x,y,-z)
Application d'un plan miroir -> Réflexion par rapport au plan(x,y)
Matrices de symétrie: 
 Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


Equations: 

A =\begin{pmatrix} 
    1 & 0 & 0 \\ 
    0 & 1 & 0 \\ 
    0 & 0 & -1 \\
\end{pmatrix}

B = 
\begin{pmatrix} 
    x \\ 
    y \\ 
    z \\
\end{pmatrix}
A * B = C

C =\begin{pmatrix} 
    x \\ 
    y \\ 
    -z \\
\end{pmatrix}

In [76]:
#Symmetrie 1 : (x,y,z) -> (x,y,-z)
#Atome 1 = K
print("Atome 1 = K")
print("Application au quatrième atome K:")
print("Position de l'atome: (x = 0, y = 0, z = 1)")
print("Nouvelle position (position équivalente): (x = 0, y = 0, z = -1)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 4 {atomno = 4}")

Atome 1 = K
Application au quatrième atome K:
Position de l'atome: (x = 0, y = 0, z = 1)
Nouvelle position (position équivalente): (x = 0, y = 0, z = -1)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [59]:
#Symmetrie 1 : (x,y,z) -> (x,y,-z)
#Atome 2 = Zn

print("Atome 2 = Zn")
print("Application à l'atome Zn:")
print("Position de l'atome: (x = 0.33333, y=0.66667,z=0.5))")
print("Nouvelle position (position équivalente): (x = 0.33333, y = 0.66667, z = -0.5)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 4 {atomno = 2}")

Atome 2 = Zn
Application à l'atome Zn:
Position de l'atome: (x = 0.33333, y=0.66667,z=0.5))
Nouvelle position (position équivalente): (x = 0.33333, y = 0.66667, z = -0.5)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [77]:
#Symmetrie 1 : (x,y,z) -> (x,y,-z)
#Atome 3 = As

print("Atome 3 = As")
print("Application à l'atome As:")
print("Position de l'atome: (x = 0.66667, y = 0.33333, z = 0.5)")
print("Nouvelle position (position équivalente): (x = 0.66667, y = 0.33333, z = -0.5)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 4 {atomno = 3}")

Atome 3 = As
Application à l'atome As:
Position de l'atome: (x = 0.66667, y = 0.33333, z = 0.5)
Nouvelle position (position équivalente): (x = 0.66667, y = 0.33333, z = -0.5)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [61]:
#Symétrie 2: (x, y, z) -> (x, x-y, z)

print("Symetrie 2 : (x,y,z) -> (x, x-y, z)")
print("Application d'un plan miroir + inversion d'ordre 2")
print("Matrices de symétrie: \n",sym[7])

Symetrie 2 : (x,y,z) -> (x, x-y, z)
Application d'un plan miroir + inversion d'ordre 2
Matrices de symétrie: 
 Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


Equations: 

A =\begin{pmatrix} 
    1 & 0 & 0 \\ 
    1 & -1 & 0 \\ 
    0 & 0 & 1 \\
\end{pmatrix}

B = 
\begin{pmatrix} 
    x \\ 
    y \\ 
    z \\
\end{pmatrix}
A * B = C

C =\begin{pmatrix} 
    x \\ 
    x-y \\ 
    z \\
\end{pmatrix}

In [66]:
#Symétrie 2
##Atome 1 = K
print("Atome 1 = K")
print("Application au quatrième atome K:")
print("Position de la molécule: (x = 0, y = 1, z = 1)")
print("Nouvelle position (position équivalente): (x = 0, y = -1, z = 1)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 8 {atomno = 6}")

Atome 1 = K
Application au quatrième atome K:
Position de la molécule: (x = 0, y = 1, z = 1)
Nouvelle position (position équivalente): (x = 0, y = -1, z = 1)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [67]:
#Symmetrie 2 : (x,y,z) -> (x, x-y, z)
#Atome 2 = Zn

print("Atome 2 = Zn")
print("Application à l'atome Zn:")
print("Position de l'atome: (x = 0.33333, y=0.66667,z=0.5))")
print("Nouvelle position (position équivalente): (x = 0.33333, y = 0.33334, z = 0.5)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 8 {atomno = 2}")

Atome 2 = Zn
Application à l'atome Zn:
Position de l'atome: (x = 0.33333, y=0.66667,z=0.5))
Nouvelle position (position équivalente): (x = 0.33333, y = 0.33334, z = 0.5)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [68]:
#Symmetrie 2 : (x,y,z) -> (x, x-y, z)
#Atome 3 = As
print("Atome 3 = As")
print("Application à l'atome As:")
print("Position de l'atome: (x = 0.66667, y = 0.33333, z = 0.5)")
print("Nouvelle position (position équivalente): (x = 0.66667, y = 0.33334, z = 0.5)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 8 {atomno = 3}")

Atome 3 = As
Application à l'atome As:
Position de l'atome: (x = 0.66667, y = 0.33333, z = 0.5)
Nouvelle position (position équivalente): (x = 0.66667, y = 0.33334, z = 0.5)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [69]:
#Symetrie 3 : (x,y,z) -> (-y, -x, z)
print("Symetrie 3 : (x,y,z) -> (-y, -x, z))")
print("Inversion d'ordre 2 § plan miroir")
print("Matrices de symétrie: \n",sym[9])

Symetrie 3 : (x,y,z) -> (-y, -x, z))
Inversion d'ordre 2
Matrices de symétrie: 
 Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


Equations: 

A =\begin{pmatrix} 
    0 & -1 & 0 \\ 
    -1 & 0 & 0 \\ 
    0 & 0 & 1 \\
\end{pmatrix}

B = 
\begin{pmatrix} 
    x \\ 
    y \\ 
    z \\
\end{pmatrix}
A * B = C

C =\begin{pmatrix} 
    -y \\ 
    -x \\ 
    z \\
\end{pmatrix}

In [70]:
#Symétrie 3
#Atome 1 = K
print("Atome 1 = K")
print("Application au dixième atome K:")
print("Position de l'atome: (x =1, y = 1, z =1)")
print("Nouvelle position (position équivalente): (x = -1, y = -1, z = 1)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 10 {atomno = 10}")

Atome 1 = K
Application au dixième atome K:
Position de l'atome: (x =1, y = 1, z =1)
Nouvelle position (position équivalente): (x = -1, y = -1, z = 1)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [71]:
#Symétrie 3: (x, y, z) -> (-y, -x, z)
#Atome 2 = Zn

print("Atome 2 = Zn")
print("Application à l'atome Zn:")
print("Position de l'atome: (x = 0.33333, y = 0.66667, z = 0.5))")
print("Nouvelle position (position équivalente): (x = -0.66667, y = -0.33337, z = 0.5)")

view = quick_view(structure, "packed")
display(view)
view.script("draw symop 10 {atomno = 2}")

Atome 2 = Zn
Application à l'atome Zn:
Position de l'atome: (x = 0.33333, y = 0.66667, z = 0.5))
Nouvelle position (position équivalente): (x = -0.66667, y = -0.33337, z = 0.5)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [72]:
#Symétrie 3: (x, y, z) -> (-y, -x, z)
#Atome 3 = As

print("Atome 3 = As")
print("Application à l'atome As:")
print("Position de l'atome: (x = 0.66667, y = 0.33333, z = 0.5)")
print("Nouvelle position (position équivalente): (x = -0.33333, y = -0.66667, z = 0.5)")
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 10 {atomno = 3}")

Atome 3 = As
Application à l'atome As:
Position de l'atome: (x = 0.66667, y = 0.33333, z = 0.5)
Nouvelle position (position équivalente): (x = -0.33333, y = -0.66667, z = 0.5)


JsmolView(layout=Layout(align_self='stretch', height='400px'))