In [5]:
from pymatgen.ext.matproj import MPRester
from pymatgen import Structure
from jupyter_jsmol.pymatgen import quick_view

from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

import numpy as np

In [6]:
with MPRester("qqtqIIM2PLMiknnf9nQO") as m: #Mettre ("USER_API_KEY")

    mp = "mp-15687"
    
    # Structure for material id
    structure = m.get_structure_by_material_id(mp)
    
    
#print (structure)

In [7]:
#Obtenir toutes les opérations de symétrie
sym = SpacegroupAnalyzer(structure).get_symmetry_operations(cartesian=False)
#print(sym)

In [24]:
#Symetrie 1 : (x,y,z) -> (x, y, -z)
print("Symetrie 1 : (x,y,z) -> (x, y, -z)")
print("Application d'un plan miroir")
print("Matrices de symétrie: \n",sym[3])

Symetrie 1 : (x,y,z) -> (x, y, -z)
Application d'un plan miroir
Matrices de symétrie: 
 Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


Equations: 

A =\begin{pmatrix} 
    1 & 0 & 0 \\ 
    0 & 1 & 0 \\ 
    0 & 0 & -1 \\
\end{pmatrix}

B = 
\begin{pmatrix} 
    x \\ 
    y \\ 
    z \\
\end{pmatrix}
A * B = C

C =\begin{pmatrix} 
    x \\ 
    y \\ 
    -z \\
\end{pmatrix}

In [25]:
##Atome 1 = K

Application à la quatrième molécule K:
position de la molécule: (x = 4.261Å, y=0,z=4.261Å)
Nouvelle position: (x = 4.261Å, y=4.261Å,z=-4.261Å)

In [26]:
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 4 {atomno = 6}")

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [7]:
#Symmetrie 1 : (x,y,z) -> (x, y, -z)

#Atome 2 = Zn

print('x, y, -z')
print("Matrice de symétrie:",sym[3])
#Changement de signe -> Plan miroir"
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 4 {atomno = 2}")

x, y, -z
Matrice de symétrie: Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [8]:
#Symmetrie 1 : (x,y,z) -> (x, y, -z)

#Atome 3 = As

print('x, y, -z')
print("Matrice de symétrie:",sym[3])
#Changement de signe -> Plan miroir"
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 4 {atomno = 3}")

x, y, -z
Matrice de symétrie: Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [9]:
#Symétrie 2: (x, y, z) -> (x, x-y, z)

#Atome 1 = K

print('x, x-y, z')
print("Matrice de symétrie:",sym[7])
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 8 {atomno = 6}")

x, x-y, z
Matrice de symétrie: Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [10]:
#Symétrie 2: (x, y, z) -> (x, x-y, z)

#Atome 2 = Zn

print('x, x-y, z')
print("Matrice de symétrie:",sym[7])
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 8 {atomno = 2}")

x, x-y, z
Matrice de symétrie: Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [11]:
#Symétrie 3: (x, y, z) -> (-y, -x, z)

#Atome 1 = K

print('-y, -x, z')
print("Matrice de symétrie:",sym[9])
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 10 {atomno = 6}")

-y, -x, z
Matrice de symétrie: Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [12]:
#Symétrie 3: (x, y, z) -> (-y, -x, z)

#Atome 2 = Zn

print('-y, -x, z')
print("Matrice de symétrie:",sym[9])
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 10 {atomno = 2}")

-y, -x, z
Matrice de symétrie: Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [13]:
#Symétrie 3: (x, y, z) -> (-y, -x, z)

#Atome 3 = As

print('-y, -x, z')
print("Matrice de symétrie:",sym[9])
view = quick_view(structure, "packed")
display(view)
view.script("draw symop 10 {atomno = 3}")

-y, -x, z
Matrice de symétrie: Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))